### ISSUE TITLE
Input channel issue 

### ISSUE THREAD

**Issue by matthewh806** [benthevining/imogen#9]
Hi Ben, I'm really interested in what you're building here both from an audio perspective and as a developer - really cool stuff!

I'm just wondering why in the FIFOWrappedEngine class about the constraint for `input.getNumChannels() == output.getNumChannels()`. I understand that when looping over for the channels you don't want to get an out of bounds error in case they're not equal, but for me on my mac for example the onboard mic is a mono input and the output is stereo - so I fail every-time at the first hurdle! 

I'm just wondering how you're getting around this on your end? 
Taking the mono input example - would it be possible in that case just to copy the data from the first channel data into a second to avoid this error? 

I'll modify the class locally to make it work for my scenario if i can, but was just thinking about whether I'd missed something? Or if there's a better way I should be approaching this

**Comment by benthevining** [comment]
Hello @matthewh806, thank you for bringing this to my attention! This does indeed seem to be an oversight in my `FIFOWrappedEngine` class. Let me look at it and see what I can do to make that class more robust.

**Comment by benthevining** [comment]
@matthewh806 I think this should be fixed by [this commit](https://github.com/benthevining/Shared-code/commit/29cfc38346921c13e8ef6eaf0a79505561ace0fc), which was merged into Imogen in [this commit](https://github.com/benthevining/imogen/commit/3423aae77adfad255805dc66023dfb2de87d14e9). 

Can you let me know if this fixes the issue for you?

Interestingly, I had never hit that assertion failure before, so it's possible that I'm unknowingly testing only with hosts that always make the number of input & output channels the same for the plugin, even if only one input channel actually has audio in it, or something... If the bug persists, can you let me know what OS & host you're getting the assert in?

This fix may be a bit naive, it's possible that if the number of input/output channels changes during runtime, this would result in some mismatched samples in the FIFOs, since it's basically a separate FIFO for each channel... but hopefully that won't be the case...

Thanks again for reporting this! ![bitmoji](https://sdk.bitmoji.com/render/panel/0c70db12-3532-4f21-954c-415c1f1f5a6f-6bd43c7f-79ea-4312-9a59-c1d3c4bd25ce-v1.png?transparent=1&palette=1&width=246)

**Comment by matthewh806** [comment]
Hello again, thanks for looking into that quickly!

I pulled the latest code changes and indeed now get a bit further into the FIFO classes before hitting an assertion on Line 128 of `AudioFIFO.h` 

```
void pushSamples (const SampleType* inputSamples, const int numSamples, const int destChannel)
    {
        jassert (destChannel >= 0 && destChannel < base.getNumChannels());
        
        const auto length = base.getNumSamples();
        
        jassert (length > 0 && base.getNumChannels() > 0);
        jassert (numSamples + storedSamples.getUnchecked(destChannel) <= length);

        ...
 }
```

That last assertion there fails. This could be an entirely related issue though, I haven't had a chance to look into it further than reporting the issue at the moment.

> Interestingly, I had never hit that assertion failure before, so it's possible that I'm unknowingly testing only with hosts that always make the number of input & output channels the same for the plugin, even if only one input channel actually has audio in it, or something

Yeah, its strange. I have two machines that I'm using - one for development and one more for audio production etc. My development machine (macOS Big Sur 11.2) hits the assertion failures - using just the standard system I/O settings. I was testing Standalone, in Reaper (which resulted in an application crash when adding the VST3 to a track and also with the the Juce Audio Plugin host (attached to the debugger in Xcode to find out where the error was occuring). 

My other machine is (running Mojave 10.14.6) and using a focusrite 18i20 audio interface and didn't experience the problem in Reaper / Plugin Host. I haven't stepped through to investigate whats going on in any more detail, so its a bit of a mystery to me as well 😄
